# Generated by Django 3.2.4 on 2021-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
