# Generated by Django 3.2.4 on 2021-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.IntegerField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
