# Generated by Django 3.2.4 on 2021-06-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
