# Generated by Django 3.2.4 on 2021-06-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=45)),
                ('nick_name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=100)),
                ('register_dttm', models.DateField(auto_now_add=True)),
                ('update_dttm', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
