# Generated by Django 3.2.4 on 2021-06-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='register_dttm',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='update_dttm',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=45),
        ),
    ]
