# Generated by Django 3.2.4 on 2021-07-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parents_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='postings.comment'),
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
