# Generated by Django 3.2.4 on 2021-06-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='user.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='user.user')),
            ],
            options={
                'db_table': 'follower_relations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='follower_user',
            field=models.ManyToManyField(related_name='followed', through='user.FollowerRelation', to='user.User'),
        ),
    ]
