# Generated by Django 3.2.4 on 2021-06-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210627_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followerrelation',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_user',
        ),
        migrations.AddField(
            model_name='followerrelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='follower', through='user.FollowerRelation', to='user.User'),
        ),
        migrations.AlterField(
            model_name='followerrelation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user'),
        ),
    ]
