# Generated by Django 3.2.4 on 2021-06-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210627_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='user.user'),
        ),
    ]
